[libraries]
assertj = "org.assertj:assertj-core:3.26.3"
avro = "org.apache.avro:avro:1.11.4"
calcite-avatica = "org.apache.calcite.avatica:avatica:1.27.0"
calcite-core = "org.apache.calcite:calcite-core:1.41.0"
calcite-server = "org.apache.calcite:calcite-server:1.41.0"
commons-cli = "commons-cli:commons-cli:1.4"
commons-dbcp2 = "org.apache.commons:commons-dbcp2:2.11.0"
cron-utils = "com.cronutils:cron-utils:9.2.1"
findbugs = "com.google.code.findbugs:jsr305:3.0.0"
flink-clients = "org.apache.flink:flink-clients:1.18.1"
flink-connector-base = "org.apache.flink:flink-connector-base:1.18.1"
flink-connector-kafka = "org.apache.flink:flink-sql-connector-kafka:3.2.0-1.18"
flink-connector-mysql-cdc = "com.ververica:flink-sql-connector-mysql-cdc:2.3.0"
flink-core = "org.apache.flink:flink-core:1.18.1"
flink-csv = "org.apache.flink:flink-csv:1.18.1"
flink-jdbc = "org.apache.flink:flink-sql-jdbc-driver-bundle:1.18.1"
flink-streaming-java = "org.apache.flink:flink-streaming-java:1.18.1"
flink-table-api-java = "org.apache.flink:flink-table-api-java:1.18.1"
flink-table-api-java-bridge = "org.apache.flink:flink-table-api-java-bridge:1.18.1"
flink-table-common = "org.apache.flink:flink-table-common:1.18.1"
flink-table-planner = "org.apache.flink:flink-table-planner_2.12:1.18.1"
flink-table-runtime = "org.apache.flink:flink-table-runtime:1.18.1"
gson = "com.google.code.gson:gson:2.9.0"
jackson = "com.fasterxml.jackson.core:jackson-core:2.15.0"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.0"
jackson-dataformat-yaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.0"
javax-annotation-api = "javax.annotation:javax.annotation-api:1.3.2"
junit-jupiter-api = "org.junit.jupiter:junit-jupiter-api:5.13.4"
junit-jupiter-engine = "org.junit.jupiter:junit-jupiter-engine:5.13.4"
junit-jupiter-params = "org.junit.jupiter:junit-jupiter-params:5.13.4"
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.7.1"
kafka-clients = "org.apache.kafka:kafka-clients:3.2.0"
kubernetes-client = "io.kubernetes:client-java:18.0.0"
kubernetes-extended-client = "io.kubernetes:client-java-extended:18.0.0"
mcp = "io.modelcontextprotocol.sdk:mcp:0.10.0"
mockito-inline = "org.mockito:mockito-inline:5.0.0"
mockito-junit-jupiter = "org.mockito:mockito-junit-jupiter:5.0.0"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.11"
slf4j-api = "org.slf4j:slf4j-api:2.0.11"
sqlline = "sqlline:sqlline:1.12.0"
quidem = "net.hydromatic:quidem:0.11"
venice = "com.linkedin.venice:venice-common:0.4.376"
venice-client = "com.linkedin.venice:venice-thin-client:0.4.376"
yaml = "org.yaml:snakeyaml:1.33"
